### ISSUE TITLE
Dataset 

### ISSUE THREAD

**Issue by sahil070197** [rodrigonogueira4/fingerprint_liveness#2]
Hi, if you cannot redistribute publically, please make it privately available for me as we are getting no response from livedet officials. I can even provide you screenshot of e-mail that i've sent a week back. I need it urgently for my project. We have an upcoming presentation.I'll be very thankful.

**Comment by sahil070197** [comment]
My email address is sahil.070197@gmail.com

**Comment by rodrigonogueira4** [comment]
It says in the license agreement that I cannot redistribute it:

Redistribution: Without prior approval from Principal Investigator, the entire
or part of the biometric dataset will not be further distributed, published,
copied or disseminated in any way or form, either for profit or not. This refers
also to further distribution of the dataset records to any other facility or
organizational unit, other than the one mentioned in the request.

**Comment by sahil070197** [comment]
Well thanks. :)

**Comment by sahil070197** [comment]
Please let me know the duration in which you got response from livedet.

**Comment by rodrigonogueira4** [comment]
It was about 3-4 days, but that was in 2014.

**Comment by sahil070197** [comment]
Thanks :) 

P.S. Please don't download any pirated stuff from internet :P
